name: CI Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_ENV_URL: https://stg.environment.io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 'latest'

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest pytest-html

      - name: Checkout Automated Test Suite Development
        uses: actions/checkout@v4
        with:
          repository: myrondizon/vault-outsourcing-qatest
          path: automated-tests

      - name: Run Cypress Tests
        working-directory: automated-tests/1-Automated-Test-Suite-Development
        run: npx cypress run || true  # Prevent workflow from stopping on failures
        env:
          CYPRESS_BASE_URL: ${{https://www.saucedemo.com/}}

      - name: Run API Tests
        working-directory: automated-tests/2-API-Testing-with-Automation/tests
        run: pytest --html=report.html --self-contained-html || true
        env:
          API_BASE_URL: ${{https://swapi.dev/api/people/1}}

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: automated-tests/1-Automated-Test-Suite-Development/cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: automated-tests/1-Automated-Test-Suite-Development/cypress/videos
          if-no-files-found: ignore

      - name: Upload API Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: automated-tests/2-API-Testing-with-Automation/tests/report.html
          if-no-files-found: ignore
